{{- if and .Values.services.frontend.enabled .Values.services.frontend.pdb.enabled }}
{{ include "sms.servicePdb" (dict "root" . "service" .Values.services.frontend "serviceName" "frontend") }}
{{- end }}
