{{- if and .Values.services.schoolOperationsService.enabled .Values.services.schoolOperationsService.pdb.enabled }}
{{ include "sms.servicePdb" (dict "root" . "service" .Values.services.schoolOperationsService "serviceName" "school-operations-service") }}
{{- end }}
