{{- if .Values.services.schoolOperationsService.enabled }}
{{ include "sms.serviceService" (dict "root" . "service" .Values.services.schoolOperationsService "serviceName" "school-operations-service") }}
{{- end }}
