CREATE TABLE IF NOT EXISTS identity.public_site_content (
    content_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    brand_label VARCHAR(120) DEFAULT 'ElevateSmart',
    hero_eyebrow VARCHAR(160),
    hero_headline VARCHAR(500),
    hero_subheadline TEXT,
    vision_title VARCHAR(200),
    vision_body TEXT,
    why_title VARCHAR(200),
    why_body TEXT,
    pricing_headline VARCHAR(200),
    pricing_body TEXT,
    contact_headline VARCHAR(200),
    contact_body TEXT,
    support_headline VARCHAR(200),
    support_body TEXT,
    founder_title VARCHAR(200),
    founder_name VARCHAR(160),
    founder_role VARCHAR(160),
    founder_message_title VARCHAR(220),
    founder_message_body TEXT,
    founder_signoff VARCHAR(200),
    primary_cta_label VARCHAR(120),
    primary_cta_url VARCHAR(255),
    secondary_cta_label VARCHAR(120),
    secondary_cta_url VARCHAR(255),
    feature_cards_json TEXT,
    role_benefits_json TEXT,
    media_gallery_json TEXT,
    testimonials_json TEXT,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO identity.public_site_content (
    content_id,
    brand_label,
    hero_eyebrow,
    hero_headline,
    hero_subheadline,
    vision_title,
    vision_body,
    why_title,
    why_body,
    pricing_headline,
    pricing_body,
    contact_headline,
    contact_body,
    support_headline,
    support_body,
    founder_title,
    founder_name,
    founder_role,
    founder_message_title,
    founder_message_body,
    founder_signoff,
    primary_cta_label,
    primary_cta_url,
    secondary_cta_label,
    secondary_cta_url,
    feature_cards_json,
    role_benefits_json,
    media_gallery_json,
    testimonials_json,
    updated_at
)
SELECT
    '00000000-0000-0000-0000-000000000001',
    'ElevateSmart',
    'The operational intelligence layer for modern education',
    'One connected campus system for admissions, academics, finance, communication, transport, and AI-assisted teaching.',
    'ElevateSmart helps institutions replace fragmented tools with a living operating system. Every workflow stays connected, every role sees the right intelligence, and every school grows with more clarity.',
    'Why we built ElevateSmart',
    'Schools should not need separate systems for onboarding, billing, communication, classroom operations, transport, and analytics. We built ElevateSmart to give institutions one shared operational language so leaders can move faster, teachers can teach better, and families can stay informed without friction.',
    'Built for institutional momentum',
    'The platform is designed to turn scattered admin effort into coordinated motion. When onboarding, subscriptions, student records, announcements, attendance, performance, and support all flow through one platform, institutions can scale without losing trust or operational control.',
    'Commercial plans aligned to rollout depth and operational capacity',
    'Choose the pricing lane that matches launch speed, institution size, and how much workflow depth you want live from day one.',
    'Talk to the team behind the platform',
    'Use this route for real conversations about rollout planning, partnerships, implementation timing, or whether the platform fits your operating model.',
    'Raise support without losing context',
    'Bring rollout blockers, production issues, access failures, and operational questions here so the platform team can triage with full context.',
    'Vision',
    'ElevateSmart Product Team',
    'Platform builders for institutions that want continuity, operational depth, and fewer disconnected systems.',
    'Education software should feel like infrastructure, not admin debt.',
    'We created ElevateSmart after seeing how often good schools were slowed down by disconnected systems and duplicate effort. The goal was never just dashboards. It was to build a dependable operating layer that helps institutions lead with more visibility, more empathy, and more follow-through across every role in the campus ecosystem.',
    'Built for schools that want operational depth, not surface-level software.',
    'Start school onboarding',
    '/onboarding',
    'See the vision',
    '/vision',
    $$[{"title":"Admissions and onboarding","description":"Launch new institutions, provision school access, and move from registration to activation with one coordinated flow.","category":"Growth","imageUrl":"/admissions-story.svg","accentColor":"#ffb663","sortOrder":1,"bullets":["Structured school onboarding","Activation workflows","Platform review visibility"]},{"title":"Academic operations","description":"Manage attendance, classes, exams, report cards, timetables, and student records from a connected operational core.","category":"Academics","imageUrl":"/academics-story.svg","accentColor":"#22d3ee","sortOrder":2,"bullets":["Attendance intelligence","Exam and timetable workflows","Student and teacher records"]},{"title":"Finance and subscriptions","description":"Track plans, billing structures, and institutional capacity with commercial data that stays connected to rollout decisions.","category":"Commercial","imageUrl":"/operational-viewpoint.svg","accentColor":"#34d399","sortOrder":3,"bullets":["Plan-aware onboarding","Fee structures","Commercial visibility for platform teams"]},{"title":"Communication and announcements","description":"Deliver parent-facing and institution-facing updates through public notices, internal announcements, and workflow-linked messaging.","category":"Communication","imageUrl":"/admissions-story.svg","accentColor":"#a78bfa","sortOrder":4,"bullets":["Public announcements","Workflow notifications","Role-aware communication paths"]},{"title":"Transport and movement visibility","description":"Coordinate routes, live movement, assignment workflows, and transport experiences across school operations.","category":"Transport","imageUrl":"/transport-network.svg","accentColor":"#f97316","sortOrder":5,"bullets":["Route and stop management","Driver and conductor views","Subscriber-facing transport access"]},{"title":"AI-assisted teaching and decision support","description":"Use AI copilot patterns for planning, visualization, examples, and institutional insight without fragmenting the main workflow.","category":"AI","imageUrl":"/ai-story.svg","accentColor":"#60a5fa","sortOrder":6,"bullets":["Teaching assistance","Learning visualizations","Decision support inside operational flows"]}]$$,
    $$[{"roleKey":"PLATFORM_ADMIN","roleLabel":"Platform Admin","headline":"Control rollout, provisioning, and system posture.","description":"View institutional growth, manage onboarding queues, control platform settings, and supervise health from a central command layer.","accentColor":"#ffb663","outcomes":["Platform-wide visibility","Commercial and onboarding control","Operational decision support"]},{"roleKey":"SCHOOL_ADMIN","roleLabel":"School Admin","headline":"Run the institution without juggling disconnected systems.","description":"Handle admissions, billing, classes, staff, transport, and communication through one operating surface.","accentColor":"#22d3ee","outcomes":["Unified school operations","Fewer fragmented tools","Cleaner institutional oversight"]},{"roleKey":"TEACHER","roleLabel":"Teachers","headline":"Stay inside the teaching flow while the system handles complexity.","description":"Access classes, attendance, analytics, resources, communication, and AI assistance without bouncing between products.","accentColor":"#a78bfa","outcomes":["Faster class execution","Better student visibility","AI support built into the workflow"]},{"roleKey":"STUDENT","roleLabel":"Students","headline":"Get a clearer picture of progress and learning access.","description":"Students can see attendance, classroom signals, resources, and learning support in a structured digital workspace.","accentColor":"#34d399","outcomes":["Progress visibility","Resource access","More consistent learning support"]},{"roleKey":"PARENT","roleLabel":"Parents","headline":"Stay informed without chasing the institution for updates.","description":"Parents gain transparent access to student context, communication, and role-specific services such as transport updates.","accentColor":"#f472b6","outcomes":["Better transparency","Faster updates","Stronger school-family trust"]},{"roleKey":"STAFF","roleLabel":"Staff and Operations","headline":"Keep support functions inside the same institutional rhythm.","description":"Administrative and support teams can work inside the same campus system rather than maintaining side channels.","accentColor":"#f59e0b","outcomes":["Less operational drift","Shared context across teams","Clearer support workflows"]},{"roleKey":"TRANSPORT","roleLabel":"Transport Teams","headline":"Operate movement and safety workflows with real context.","description":"Drivers, conductors, and transport managers work with route-aware views designed for live operational use.","accentColor":"#38bdf8","outcomes":["Route visibility","Role-specific consoles","Safer day-to-day coordination"]}]$$,
    $$[{"sectionKey":"hero","imageUrl":"/operational-viewpoint.svg","fallbackImageUrl":"/operational-viewpoint.svg","altText":"Platform operational illustration","caption":"A text-free visual that mirrors the connected operating model described on the landing page."},{"sectionKey":"story","imageUrl":"/institution-flow.svg","fallbackImageUrl":"/institution-flow.svg","altText":"Institutional workflow illustration","caption":"Signals moving across onboarding, academics, communication, transport, and finance."},{"sectionKey":"founder","imageUrl":"/institution-flow.svg","fallbackImageUrl":"/institution-flow.svg","altText":"Institutional systems illustration","caption":"A connected systems visual for the platform vision story."}]$$,
    $$[{"quote":"We finally stopped stitching together admissions spreadsheets, transport chats, and fee follow-ups. The platform gave our leadership team one operational picture.","authorName":"Asha Nair","authorRole":"Principal","organization":"North Ridge Academy","avatarUrl":"/operational-viewpoint.svg","accentColor":"#22d3ee","sortOrder":1},{"quote":"The rollout felt grounded because the platform team understood institutional workflow, not just software setup. That made the difference for our staff adoption.","authorName":"Rohan Bedi","authorRole":"Operations Lead","organization":"Bakshi Memorial Public School","avatarUrl":"/institution-flow.svg","accentColor":"#ffb663","sortOrder":2},{"quote":"Teachers got clarity instead of another admin portal. Attendance, notices, and learning support now feel connected instead of fragmented.","authorName":"Meera Joshi","authorRole":"Academic Coordinator","organization":"Summit Public School","avatarUrl":"/ai-story.svg","accentColor":"#a78bfa","sortOrder":3}]$$,
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (SELECT 1 FROM identity.public_site_content);

CREATE TABLE IF NOT EXISTS identity.public_inquiry_requests (
    inquiry_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    inquiry_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    full_name VARCHAR(160) NOT NULL,
    email VARCHAR(160) NOT NULL,
    organization VARCHAR(160),
    school_name VARCHAR(160),
    phone VARCHAR(60),
    subject VARCHAR(220) NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS identity.public_media_assets (
    asset_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    asset_key VARCHAR(120) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(120) NOT NULL,
    file_size BIGINT NOT NULL,
    content_data BYTEA NOT NULL,
    created_by VARCHAR(160),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_public_media_assets_asset_key
    ON identity.public_media_assets(asset_key);

