{{- if and .Values.services.financeService.enabled .Values.services.financeService.autoscaling.enabled }}
{{ include "sms.serviceHpa" (dict "root" . "service" .Values.services.financeService "serviceName" "finance-service") }}
{{- end }}
