package com.sms.schoolops.api;

import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

public class AttendanceManagementDtos {
    public record AttendancePolicyResponse(
            UUID policyId,
            UUID schoolId,
            int warningThreshold,
            int criticalThreshold,
            List<String> enabledChannels,
            boolean autoAbsentEnabled,
            int autoAbsentMinutes,
            boolean gpsEnabled,
            String gpsMode,
            Double geofenceLatitude,
            Double geofenceLongitude,
            Double geofenceRadiusMeters,
            boolean voiceEnabled,
            boolean faceEnabled,
            boolean aiPredictionEnabled,
            boolean reminderEnabled,
            String reminderFrequency,
            double faceConfidenceThreshold,
            Instant createdAt,
            Instant updatedAt
    ) {}

    public record AttendancePolicyUpdateRequest(
            @Min(1) @Max(100) Integer warningThreshold,
            @Min(1) @Max(100) Integer criticalThreshold,
            List<String> enabledChannels,
            Boolean autoAbsentEnabled,
            @Min(0) Integer autoAbsentMinutes,
            Boolean gpsEnabled,
            String gpsMode,
            Double geofenceLatitude,
            Double geofenceLongitude,
            Double geofenceRadiusMeters,
            Boolean voiceEnabled,
            Boolean faceEnabled,
            Boolean aiPredictionEnabled,
            Boolean reminderEnabled,
            String reminderFrequency,
            Double faceConfidenceThreshold
    ) {}

    public record AttendanceSubjectOption(UUID subjectId, String subjectName, String subjectCode) {}

    public record AttendanceClassContext(
            UUID classId,
            String className,
            String sectionName,
            String academicYear,
            boolean classTeacher,
            List<AttendanceSubjectOption> subjects,
            List<Integer> periods
    ) {}

    public record AttendanceContextResponse(
            AttendancePolicyResponse policy,
            boolean canMarkAttendance,
            boolean canManageAttendance,
            boolean canViewOwnAttendance,
            List<AttendanceClassContext> classes,
            List<AttendanceSessionSummary> recentSessions
    ) {}

    public record CreateAttendanceSessionRequest(
            @NotNull UUID classId,
            @NotNull UUID subjectId,
            @NotNull LocalDate attendanceDate,
            @NotNull @Min(1) Integer periodNumber,
            UUID timetableSlotId
    ) {}

    public record AttendanceSessionSummary(
            UUID sessionId,
            UUID schoolId,
            UUID classId,
            String className,
            String sectionName,
            UUID subjectId,
            String subjectName,
            UUID teacherUserId,
            String teacherName,
            LocalDate attendanceDate,
            Integer periodNumber,
            UUID timetableSlotId,
            String sessionStatus,
            String gpsVerificationStatus,
            String gpsMessage,
            Double gpsDistanceMeters,
            long totalStudents,
            long presentCount,
            long absentCount,
            long lateCount,
            long excusedCount,
            boolean editable,
            boolean autoGenerated,
            Instant submittedAt,
            Instant lastEditedAt
    ) {}

    public record AttendanceAuditEntry(
            UUID auditLogId,
            UUID attendanceId,
            UUID studentUserId,
            String studentName,
            String previousStatus,
            String newStatus,
            String editReason,
            String changedBy,
            String changedRole,
            Instant createdAt
    ) {}

    public record AttendanceRosterStudent(
            UUID attendanceId,
            UUID studentUserId,
            String fullName,
            String rollNumber,
            String profilePhotoUrl,
            String attendanceStatus,
            String captureSource,
            String absenceReasonCategory,
            String absenceReasonDescription,
            Instant lastModifiedAt
    ) {}

    public record AttendanceSessionDetailResponse(
            AttendanceSessionSummary session,
            AttendancePolicyResponse policy,
            boolean editable,
            List<AttendanceRosterStudent> roster,
            List<AttendanceAuditEntry> audits
    ) {}

    public record UpdateAttendanceStudentRequest(
            @NotBlank String attendanceStatus,
            String captureSource,
            String editReason
    ) {}

    public record BulkMarkRequest(
            @NotBlank String attendanceStatus,
            String captureSource
    ) {}

    public record VoiceCommandRequest(@NotBlank String transcript) {}

    public record VoiceCommandMatch(
            String rollNumber,
            String studentName,
            String attendanceStatus,
            boolean applied,
            String reason
    ) {}

    public record VoiceCommandResponse(
            String transcript,
            List<VoiceCommandMatch> commands,
            int appliedCount,
            int rejectedCount
    ) {}

    public record GpsVerificationRequest(
            @NotNull Double latitude,
            @NotNull Double longitude,
            Double accuracyMeters
    ) {}

    public record GpsVerificationResponse(
            String verificationStatus,
            boolean allowed,
            Double distanceMeters,
            String message,
            String mode
    ) {}

    public record FaceScanRequest(UUID hintedStudentId, String captureReference) {}

    public record FaceScanResponse(
            UUID matchedStudentId,
            String matchedStudentName,
            Double confidence,
            boolean autoApplied,
            String providerStatus,
            String reviewOutcome,
            String message
    ) {}

    public record SubmitAttendanceSessionRequest(String submitNote, Boolean forceSubmitOutsideGeofence) {}

    public record EditAttendanceRecordRequest(@NotBlank String attendanceStatus, @NotBlank String editReason) {}

    public record AbsenceReasonRequest(
            @NotNull UUID attendanceId,
            @NotBlank String category,
            String description
    ) {}

    public record AbsenceReasonResponse(
            UUID absenceReasonId,
            UUID attendanceId,
            String category,
            String description,
            String reviewStatus,
            Instant createdAt
    ) {}

    public record AttendanceCalendarDay(
            LocalDate date,
            String status,
            int periods,
            long presentCount,
            long absentCount,
            long lateCount
    ) {}

    public record AttendanceHeatmapPoint(LocalDate date, long score, String color) {}

    public record AttendanceDailyStatus(
            LocalDate date,
            String status,
            Integer periodNumber,
            String subjectName,
            String markedBy
    ) {}

    public record StudentAttendanceSummaryResponse(
            UUID studentUserId,
            String studentName,
            String className,
            String sectionName,
            String preset,
            LocalDate fromDate,
            LocalDate toDate,
            double attendancePercentage,
            long presentDays,
            long absentDays,
            long lateDays,
            long excusedDays,
            String warningLevel,
            int warningThreshold,
            int criticalThreshold,
            List<AttendanceCalendarDay> calendar,
            List<AttendanceHeatmapPoint> heatmap,
            List<AttendanceDailyStatus> daily
    ) {}

    public record AttendanceTrendPoint(LocalDate date, long total, long present, long absent, long late, long excused) {}

    public record AttendanceClassOverview(
            UUID classId,
            String className,
            String sectionName,
            double attendancePercentage,
            long totalMarks,
            long presentCount,
            long absentCount,
            long lateCount
    ) {}

    public record AttendanceRiskStudentRow(
            UUID studentUserId,
            String fullName,
            String rollNumber,
            UUID classId,
            String className,
            String sectionName,
            double attendancePercentage,
            double predictedAttendancePercentage,
            String riskLevel,
            long absentCount,
            long lateCount,
            boolean alertActive
    ) {}

    public record AttendanceOverviewResponse(
            AttendancePolicyResponse policy,
            long totalSessions,
            long submittedSessions,
            long draftSessions,
            long totalStudents,
            double schoolAttendancePercentage,
            List<AttendanceTrendPoint> trend,
            List<AttendanceClassOverview> byClass,
            List<AttendanceRiskStudentRow> riskStudents
    ) {}

    public record AttendanceHeatmapResponse(LocalDate fromDate, LocalDate toDate, List<AttendanceHeatmapPoint> items) {}

    public record AttendanceCalendarResponse(UUID studentUserId, LocalDate fromDate, LocalDate toDate, List<AttendanceCalendarDay> items) {}

    public record AttendanceRiskResponse(LocalDate snapshotDate, List<AttendanceRiskStudentRow> students) {}

    public record ClassMonitorResponse(List<AttendanceSessionSummary> sessions, List<AttendanceRiskStudentRow> riskStudents) {}
}
