{{- if .Values.global.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secrets.existingSecret }}
  labels:
{{ include "sms.commonLabels" (dict "root" . "serviceName" "sms-secrets") | indent 4 }}
type: Opaque
stringData:
{{ toYaml .Values.global.secrets.data | indent 2 }}
{{- end }}
