{{- if and .Values.services.aiInteractionService.enabled .Values.services.aiInteractionService.pdb.enabled }}
{{ include "sms.servicePdb" (dict "root" . "service" .Values.services.aiInteractionService "serviceName" "ai-interaction-service") }}
{{- end }}
