{{- if and .Values.services.subscriptionService.enabled .Values.services.subscriptionService.autoscaling.enabled }}
{{ include "sms.serviceHpa" (dict "root" . "service" .Values.services.subscriptionService "serviceName" "subscription-service") }}
{{- end }}
