{{- if .Values.services.subscriptionService.enabled }}
{{ include "sms.serviceService" (dict "root" . "service" .Values.services.subscriptionService "serviceName" "subscription-service") }}
{{- end }}
