apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sms-platform
  namespace: argocd
spec:
  project: sms
  source:
    repoURL: REPLACE_ME_GIT_REPO_URL
    targetRevision: develop
    path: infra/helm/sms-platform
    helm:
      valueFiles:
        - values.yaml
        - values-gitops-kind.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: sms
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
