apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sms-secrets
  namespace: sms
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-local
  target:
    name: sms-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: sms/platform
