apiVersion: v1
kind: Service
metadata:
  name: emqx
spec:
  type: ClusterIP
  selector:
    app: emqx
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
    - name: http-api
      port: 8083
      targetPort: http-api
    - name: dashboard
      port: 18083
      targetPort: dashboard
