{{- if and .Values.services.mcpServer.enabled .Values.services.mcpServer.pdb.enabled }}
{{ include "sms.servicePdb" (dict "root" . "service" .Values.services.mcpServer "serviceName" "mcp-server") }}
{{- end }}
