type RenderedResponse = {
  type: string;
  data: Record<string, any> | null;
  meta?: Record<string, any> | null;
  thought?: string | null;
};

function escapeHtml(value: string) {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function normalizeTitle(response: RenderedResponse) {
  const candidate = response.data?.title || response.meta?.intent || 'Aura Artifact';
  return String(candidate).trim() || 'Aura Artifact';
}

function toMarkdown(response: RenderedResponse): string {
  const title = normalizeTitle(response);
  const lines: string[] = [`# ${title}`];

  if (response.thought) {
    lines.push('', `> ${response.thought}`);
  }

  if (typeof response.data?.summary === 'string' && response.data.summary.trim()) {
    lines.push('', response.data.summary.trim());
  }

  if (typeof response.data?.text === 'string' && response.data.text.trim()) {
    lines.push('', response.data.text.trim());
  }

  if (Array.isArray(response.data?.insights) && response.data.insights.length) {
    lines.push('', '## Insights');
    response.data.insights.forEach((insight: string) => {
      lines.push(`- ${insight}`);
    });
  }

  if (Array.isArray(response.data?.rows) && response.data.rows.length) {
    const rows = response.data.rows as Array<Record<string, unknown>>;
    const keys = Object.keys(rows[0] || {});
    if (keys.length) {
      lines.push('', '## Table');
      lines.push(`| ${keys.join(' | ')} |`);
      lines.push(`| ${keys.map(() => '---').join(' | ')} |`);
      rows.forEach((row) => {
        lines.push(`| ${keys.map((key) => String(row[key] ?? '—')).join(' | ')} |`);
      });
    }
  }

  if (response.type === 'composed' && Array.isArray(response.data?.sections)) {
    lines.push('', '## Sections');
    response.data.sections.forEach((section: any) => {
      if (section?.title) lines.push('', `### ${section.title}`);
      if (section?.kind === 'markdown' && typeof section.content === 'string') {
        lines.push(section.content);
      } else if (section?.kind === 'snapshot' && section?.data && typeof section.data === 'object') {
        Object.entries(section.data).forEach(([key, value]) => {
          lines.push(`- ${key}: ${typeof value === 'object' ? JSON.stringify(value) : String(value ?? '—')}`);
        });
      } else if (section?.kind === 'checklist' && Array.isArray(section.items)) {
        section.items.forEach((item: any) => lines.push(`- ${typeof item === 'string' ? item : item.label || 'Untitled item'}`));
      } else if (section?.kind === 'suggestions' && Array.isArray(section.items)) {
        section.items.forEach((item: any) => lines.push(`- ${typeof item === 'string' ? item : item.label || 'Untitled suggestion'}`));
      } else if (section?.kind === 'smart_ui' && section?.response) {
        if (Array.isArray(section.response?.insights) && section.response.insights.length) {
          lines.push('#### Insights');
          section.response.insights.forEach((insight: string) => lines.push(`- ${insight}`));
        }
        if (Array.isArray(section.response?.components) && section.response.components.length) {
          lines.push('#### Components');
          section.response.components.forEach((component: any) => {
            const componentTitle = component?.title || component?.type || 'artifact';
            lines.push(`- ${componentTitle}`);
          });
        }
      } else {
        lines.push('```json', JSON.stringify(section, null, 2), '```');
      }
    });
  }

  if (lines.length === 1) {
    lines.push('', '```json', JSON.stringify(response.data ?? {}, null, 2), '```');
  }

  return lines.join('\n');
}

function toHtml(response: RenderedResponse): string {
  const title = escapeHtml(normalizeTitle(response));
  const markdown = escapeHtml(toMarkdown(response)).replace(/\n/g, '<br />');
  return `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>${title}</title>
    <style>
      body { font-family: Inter, Arial, sans-serif; padding: 40px; color: #0f172a; }
      .wrap { max-width: 860px; margin: 0 auto; }
      h1 { font-size: 28px; margin: 0 0 12px; }
      .meta { color: #475569; margin-bottom: 24px; }
      .content { line-height: 1.7; white-space: normal; }
      .panel { border: 1px solid #cbd5e1; border-radius: 16px; padding: 20px; background: #f8fafc; }
    </style>
  </head>
  <body>
    <div class="wrap">
      <h1>${title}</h1>
      <div class="meta">Generated by Aura Assistant</div>
      <div class="panel content">${markdown}</div>
    </div>
  </body>
</html>`;
}

function downloadFile(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export async function copyArtifactSummary(response: RenderedResponse) {
  await navigator.clipboard.writeText(toMarkdown(response));
}

export function downloadArtifactMarkdown(response: RenderedResponse) {
  const title = normalizeTitle(response).toLowerCase().replace(/[^a-z0-9]+/g, '-');
  downloadFile(`${title || 'aura-artifact'}.md`, toMarkdown(response), 'text/markdown;charset=utf-8');
}

export function downloadArtifactDoc(response: RenderedResponse) {
  const title = normalizeTitle(response).toLowerCase().replace(/[^a-z0-9]+/g, '-');
  downloadFile(`${title || 'aura-artifact'}.doc`, toHtml(response), 'application/msword;charset=utf-8');
}

export function printArtifact(response: RenderedResponse) {
  const popup = window.open('', '_blank', 'noopener,noreferrer,width=960,height=800');
  if (!popup) return;
  popup.document.open();
  popup.document.write(toHtml(response));
  popup.document.close();
  popup.focus();
  popup.print();
}
