{{- if and .Values.services.communicationService.enabled .Values.services.communicationService.autoscaling.enabled }}
{{ include "sms.serviceHpa" (dict "root" . "service" .Values.services.communicationService "serviceName" "communication-service") }}
{{- end }}
