{{- if and .Values.services.communicationService.enabled .Values.services.communicationService.pdb.enabled }}
{{ include "sms.servicePdb" (dict "root" . "service" .Values.services.communicationService "serviceName" "communication-service") }}
{{- end }}
