{{- if and .Values.services.apiGateway.enabled .Values.services.apiGateway.pdb.enabled }}
{{ include "sms.servicePdb" (dict "root" . "service" .Values.services.apiGateway "serviceName" "api-gateway") }}
{{- end }}
