apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sms
  namespace: argocd
spec:
  description: SMS platform GitOps project
  sourceRepos:
    - '*'
  destinations:
    - namespace: sms
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: external-secrets
      server: https://kubernetes.default.svc
    - namespace: vault
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

