{{- if .Values.services.schoolOnboardingService.enabled }}
{{ include "sms.serviceDeployment" (dict "root" . "service" .Values.services.schoolOnboardingService "serviceName" "school-onboarding-service") }}
{{- end }}
