{{- if and .Values.services.schoolOnboardingService.enabled .Values.services.schoolOnboardingService.autoscaling.enabled }}
{{ include "sms.serviceHpa" (dict "root" . "service" .Values.services.schoolOnboardingService "serviceName" "school-onboarding-service") }}
{{- end }}
