{{- if and .Values.services.schoolOnboardingService.enabled .Values.services.schoolOnboardingService.pdb.enabled }}
{{ include "sms.servicePdb" (dict "root" . "service" .Values.services.schoolOnboardingService "serviceName" "school-onboarding-service") }}
{{- end }}
